name: Publish package to the Maven Central Repository and GitHub Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Publish semver tags as releases.
    tags:
      - 'v*.*.*'

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to the Maven Central Repository
        run: mvn -B clean deploy -Dgpg.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Publish to GitHub Packages
        run: mvn -B clean deploy -Dgpg.skip=true -Dgithub=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
